name: Build & Publish octo4a Debug APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable octo4a-1
      run: chmod +x ./gradlew
    - name: Build with Gradle octo4a-2
      run: ./gradlew build
    - name: Build Debug APK octo4a-3
      run: ./gradlew assembleDebug
    - name: Releasing using Hub octo4a-4
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
